### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by mgotovac** [polagoab/merge-properties-maven-plugin#7]
Hi,

I'm trying to use your plugin but I'm getting the following error during the build:
`[ERROR] Failed to execute goal org.polago.maven.plugins:merge-properties-maven-plugin:1.1:merge (merge-en) on project eppeople: Execution merge-en of goal org.polago.maven.plugins:merge-properties-maven-plugin:1.1:merge failed: Unable to load the mojo 'merge' in the plugin 'org.polago.maven.plugins:merge-properties-maven-plugin:1.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/polago/maven/plugins/mergeproperties/MergePropertiesMojo : Unsupported major.minor version 51.0`

My project uses JDK 1.6. Could that be the reason?

**Comment by perlan** [comment]
Hi,

Yes, I would say that this is probobly the reason. The plugin requires JDK 1.7 and maven 3.0.4.

**Comment by mgotovac** [comment]
Any special reason why JDK 1.7 is required when it can be built with 1.6 without any problems?

**Comment by perlan** [comment]
I actually don't know if the plugin builds or even runs on JDK 1.6. I don't have a JDK 1.6 version available. Have you built and tested it on JDK 1.6?

**Comment by mgotovac** [comment]
Yes, after I built it with 1.6 the plugin worked like a charm

**Comment by perlan** [comment]
Great to hear that it worked. Care to submit a pull request with your changes?

**Comment by mgotovac** [comment]
Yes, I will

**Comment by mgotovac** [comment]
Pull request submitted
