### ISSUE TITLE
Timestamp at the top of merged properties file

### ISSUE THREAD

**Issue by mgotovac** [polagoab/merge-properties-maven-plugin#9]
Hi,

Is there a way to disable adding a commented timestamp at the top of the output file (eg. #Fri Mar 31 16:27:34 CEST 2017)?

Thanks!

**Comment by perlan** [comment]
I'm sorry but the comment timestamp is written by the standard java.util.Properties class that is used for merging all properties. To avoid the comment, the plugin needs to implements it's own serializer for java properties files. See also #4 and #8. Pull request are always welcome.
